### ISSUE TITLE
nonsequitur in workflow tutorial

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#22]
For review: openjournals/joss-reviews#5701

In https://lavaanextra.remi-theriault.com/articles/fullworkflow.html
the CFA example ends by removing items with the lowest loadings in order to improve fit.  This suggestion is provided without any justification or citation that it is a good idea.  Unreliable items can still be included in a model that accurately depicts their relationships with common factors (including method factors that might explain correlated residuals).  Because this package is apparently targeted to "beginners" (in the Statement of Need), I would recommend excluding any example of a workflow that does not demonstrate best practices.

**Comment by rempsyc** [comment]
Thank you, I agree that we want to demonstrate best practice. I would like to revise this example to reflect that.

In this particular case, I think I simply want to demonstrate the use of the `remove.items` feature, which is not showcased elsewhere. This can be helpful in some scenarios. Say for instance that we are running a big study with lots of scales, and participants can only answer so many questionnaires before they tire. So we want to develop a short scale with only x number of items per dimension. We decide to identify which items to keep by relying on the loadings (so it is not about improving fit anymore).

If I revise the vignette to give this hypothetical scenario to showcase `remove.items`, is this more acceptable or still bad practice?

**Comment by TDJorgensen** [comment]
> we want to develop a short scale with only x number of items per dimension

I agree that's a good practical example to consider, which would demonstrate the value of `cfa_fit_plot(remove.items=)`.  Perhaps the workflow could tie in estimation of reliability for composites with all items vs. dropping items.  You could use `psych::alpha` to estimate reliability of composites with all items, as well as dropping each item (printed under `Reliability if an item is dropped`), although alpha might change very little because of the tau-equivalence assumption.  You could also loop over items with the `semTools::compRelSEM()` function to calculate "omega" instead.

```
data(cattell, package = "psych") # correlation matrix
mod <- write_lavaan(latent = list(G = rownames(cattell)))
fit <- cfa(mod, sample.cov = cattell, sample.nobs = 277)
compRelSEM(fit) # reliability of composite with 12 indicators
## estimate reliability of all 11-indicator composites
data.frame(Drop = rownames(cattell),
           Omega = sapply(rownames(cattell), USE.NAMES = FALSE,
                          function(i) compRelSEM(fit, omit.indicators = i)))
```

That's just for empirical information about items that would lower reliability if dropped. You would of course want to drop multiple items to shorten a scale, then calculate the composite of that reliability.  But you can pass multiple indicators to the `compRelSEM(omit.indicators =)` argument, if you want to estimate it from the larger model first.  That always opens a Pandora's box of "which model is right?", which is an important assumption for factor-model reliability estimation.

**Comment by rempsyc** [comment]
I like reporting omega, but also report alpha for "backward compatibility". I usually use `psych::omega`, and didn't know about `semTools::compRelSEM()`, I will look into it! (`psych::omega` also does not output the “Reliability if an item is dropped” section)

Oh, ok, I see, it is better for SEM (of course, coming from `semTools` :) ) because you can simply provide it your fit object instead of manually have to feed it the items. It fits great with the workflow in this case!

Using `psych::alpha()` fits not as well in the script because I have to give it the data manually. Here's what I've done so far, am I off-track?

https://lavaanextra.remi-theriault.com/articles/fullworkflow.html#estimation-of-items-reliability

---

I'm not sure if I've done this in the most efficient way. It seemed that I needed to repeat my code for each dimension, for both alpha and omega. If I had more time, my reflex would be to turn this `semTools::compRelSEM()` step into a function! But perhaps I should ask for a feature request in `semTools` instead :P

**Comment by TDJorgensen** [comment]
The example definitely gets more complex due to modeling more than 1 dimension.  I don't think it is necessary to include omega, since the focus is just to illustrate when (and why) the `remove.items=` argument can be useful. The `alpha()` examples serve as a quick hypothetical justification, which is all you need.
