### ISSUE TITLE
lavaan_ind() is actually more general

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#24]
For review: openjournals/joss-reviews#5701

`lavaan_ind()` only selects rows with `$op == ":="`, which can be any user-defined parameters, not merely indirect effects.  This could have strange consequences for labeling when indirect effects aren't the only type of user-defined parameter in a model (e.g., when slopes differ across groups):

```
fit <- sem(' x1 ~ c(a, b)*x2 ', data = HolzingerSwineford1939,
           group = "school", constraints = 'moderated_slope := a - b')
lavaan_ind(fit)
```

It would be wise to either (a) include a more thorough check for selecting only the rows of parameters that are indirect effects, or (b) to rename the function to reflect it being more general.  There could be an argument to request any specific character (your example can use your arrow: `"\u2192"`) to replace underscores, or even accept a vector of replacements if they are not all the same.

**Comment by rempsyc** [comment]
> It would be wise to either (a) include a more thorough check for selecting only the rows of parameters that are indirect effects

Indeed, just like for total effects. I thought it made sense to lump them together in the mediation section of the model, but for `lavaan_ind()`, total effects and the moderated slope example you give (a good one) also come out with, which is inconsistent.

Is there any unique markers of indirect effects vs other user-defined parameters? I cannot find any, except perhaps the asterisk * which does not come up with the moderated slope example (but does for total effect, so not perfect). If not then perhaps I will have no choice but to change the function name and purpose to a more general one like you mention. Then I wonder what a good name would be.

Interestingly, `?model.syntax` does not include the `:=` operator in its list of seven operators (is it because it came later and the documentation was not updated, or perhaps it is not necessary in this section?). To be consistent with this family of functions, I am thinking something like `lavaan_user_defined_parameters()` but it is rather long, but shorter versions are not very clear: `lavaan_user_defined()`, `lavaan_user()`, `lavaan_parameters()`, `lavaan_custom()`, `lavaan_other()`...

**Comment by rempsyc** [comment]
`lavaan_ind()` is now named `lavaan_defined()`, and has the following new arguments (with their defaults):

```r
underscores_to_symbol = "\u2192",
lhs_name = "User-Defined Parameter",
rhs_name = "Paths",
```

So with your example we now get:

``` r
library(lavaan)
library(lavaanExtra)
fit <- sem(' x1 ~ c(a, b)*x2 ', data = HolzingerSwineford1939,
           group = "school", constraints = 'moderated_slope := a - b')
lavaan_defined(fit, underscores_to_symbol = "", nice_table = TRUE)
```

<img src="https://i.imgur.com/4PwDT0s.png" width="809" />

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
> There could be an argument to [...] accept a vector of replacements if they are not all the same.

Done as well:

``` r
library(lavaan)
library(lavaanExtra)
latent <- list(visual = paste0("x", 1:3), textual = paste0("x", 4:6), speed = paste0("x", 7:9))
mediation <- list(speed = "visual", textual = "visual", visual = c("ageyr", "grade"))
indirect <- list(IV = c("ageyr", "grade"), M = "visual", DV = c("speed", "textual"))
HS.model <- write_lavaan(mediation, indirect = indirect, latent = latent, label = TRUE)
fit <- sem(HS.model, data = HolzingerSwineford1939)
lavaan_defined(fit, underscores_to_symbol = c("*", "+", "|", "~"), nice_table = TRUE)
```

<img src="https://i.imgur.com/0J9xKlS.png" width="1060" />

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
