### ISSUE TITLE
write_lavaan(mediation=) is unnecessary

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#25]
For review: openjournals/joss-reviews#5701

`write_lavaan()` internally handles the `mediation=` and `regression=` arguments identically, except that the `label=` argument is additionally passed to `process_vars()` for `mediation=` components. 

```
    if (!is.null(mediation)) {
        mediation <- process_vars(mediation, symbol = "~", label = label, 
            title = "[-----------Mediations (named paths)-----------]")
    }
    if (!is.null(regression)) {
        regression <- process_vars(regression, symbol = "~", 
            title = "[---------Regressions (Direct effects)---------]")
    }
```

I assume the default is `process_vars()` is `label = FALSE`, but that function does not appear to be from this package (nor did a `??` query return anything).
This is perfectly consistent with the help-page description, but I had to inspect the source code to understand why it was necessary.  It does not appear to be necessary, since one could simply pass the same information from mediation to the regression argument, if the source code merely called `regression <- process_vars(regression, symbol = "~", label = label, ...)` once.  The examples about mediation already show users that the `label=` argument is necessary to define indirect effects. 

I can't image, but is there some special scenario that includes regression paths in an SEM that are not part of indirect effects of interest?  Maybe to control for covariates, those effects are not of interest?  But those can always be ignored in a table of results.  To exclude them from indirect effects, the `label=` argument could be a character vector of variable names to include (implying `TRUE` when not empty or `NULL`).

**Comment by rempsyc** [comment]
`process_vars()` is an internal function not useful for users, that is mainly useful for adding the + symbols, other operators, and section headers in a straightforward manner. It was not accessible before because I kept it within `write_lavaan()`. I have now pulled it out so the following will work:
```r
View(lavaanExtra:::process_vars)
```
However, I do not want to document it (using the `@noRd` tag), so `?process_vars()` will still not work, on purpose.

The `label` is indeed `FALSE` by default, and the differences are (1) the ability to name paths for mediations but not for regressions, and (2) the difference in section headers. I know it sounds a bit unnecessary, but I like to be able to accommodate different scenarios in the model specification output, so one section is clearly labeled regression, and the other clearly mediation, and so they can be used independently or jointly, etc. In this way people have (marginally) more freedom to express their model in the way they prefer.

So I do not think merging both arguments into one would be as satisfying to me. Maybe I misunderstood what you mean, if this is the case, please do not hesitate to clarify.
